//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public int EmployeeID { get; set; }
        public string LoginID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
