//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int PatientID { get; set; }
        public int SecretaryID { get; set; }
        public int ServiceID { get; set; }
        public int DoctorID { get; set; }
        public Nullable<System.DateTime> Appointment { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Doctor_Services Doctor_Services { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Secretary Secretary { get; set; }
    }
}
